In [3]:
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import plot_tree

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
# Autos dataset

In [5]:
df = pd.read_csv('autos_dataset.csv')
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [7]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [8]:
df['num-of-cylinders'].replace({'four':4, 'six':6, 'five':5,
                                'three':3, 'twelve':12, 'two':2, 'eight':8}, inplace=True)

C:\Users\Victus\AppData\Local\Temp\ipykernel_21412\657570370.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['num-of-cylinders'].replace({'four':4, 'six':6, 'five':5,
C:\Users\Victus\AppData\Local\Temp\ipykernel_21412\657570370.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['num-of-cylinders'].replace({'four':4, 'six':6, 'five':5,

In [9]:
df['num-of-cylinders'].replace({'four':4, 'six':6, 'five':5,
                                'three':3, 'twelve':12, 'two':2, 'eight':8}, inplace=True)

In [10]:
df['num-of-cylinders'].unique()

array([ 4,  6,  5,  3, 12,  2,  8])

In [11]:
df.replace({'?':np.nan}, inplace=True)

In [12]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    int64
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(6), object(15)
memory usage: 41.8+ KB

In [14]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [15]:
df.drop(['make','fuel-type', 'aspiration','engine-type','normalized-losses',
         'num-of-doors', 'bore', 'stroke','fuel-system',
         'body-style', 'drive-wheels', 'engine-location'], axis=1, inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   wheel-base         205 non-null    float64
 2   length             205 non-null    float64
 3   width              205 non-null    float64
 4   height             205 non-null    float64
 5   curb-weight        205 non-null    int64
 6   num-of-cylinders   205 non-null    int64
 7   engine-size        205 non-null    int64
 8   compression-ratio  205 non-null    float64
 9   horsepower         203 non-null    object
 10  peak-rpm           203 non-null    object
 11  city-mpg           205 non-null    int64
 12  highway-mpg        205 non-null    int64
 13  price              201 non-null    object
dtypes: float64(5), int64(6), object(3)
memory usage: 22.6+ KB

In [17]:
df.isna().sum()

symboling            0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
num-of-cylinders     0
engine-size          0
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [18]:
# Convert columns to numeric first
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['peak-rpm'] = pd.to_numeric(df['peak-rpm'], errors='coerce')
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

# Fill missing values with mean
df['price'] = df['price'].fillna(df['price'].mean())
df['peak-rpm'] = df['peak-rpm'].fillna(df['peak-rpm'].mean())
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

In [19]:
df.isna().sum()

symboling            0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
num-of-cylinders     0
engine-size          0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [20]:
X = df.drop(['price'], axis=1)
y = df['price']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [22]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (164, 13)
X_test shape: (41, 13)
y_train shape: (164,)
y_test shape: (41,)

In [23]:
dt_reg = DecisionTreeRegressor()
dt_reg.fit(X_train, y_train)

DecisionTreeRegressor()

In [24]:
y_pred = dt_reg.predict(X_test)

In [25]:
mse = mean_squared_error(y_test, y_pred)

print("Mean Squared Error:", mse)

Mean Squared Error: 7355843.547045746

In [26]:
rmse = np.sqrt(mse)

print("Root Mean Squared Error:", rmse)

Root Mean Squared Error: 2712.165840623642

In [27]:
mae = mean_absolute_error(y_test, y_pred)

print("Mean Absolute Error:", mae)

Mean Absolute Error: 1791.6813493508068

In [28]:
r2 = r2_score(y_test, y_pred)

print("R2 Score:", r2)
print("Decision Tree Testing Accuracy:", round(r2 * 100, 2), "%")

R2 Score: 0.9056605395891906
Decision Tree Testing Accuracy: 90.57 %

In [29]:
from sklearn.ensemble import RandomForestRegressor

In [30]:
rf_reg = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [31]:
rf_reg.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [32]:
y_pred_rf = rf_reg.predict(X_test)

In [33]:
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest R2 Score:", r2_rf)
print("Random Forest Testing Accuracy:", round(r2_rf * 100, 2), "%")

Random Forest R2 Score: 0.9354879172113387
Random Forest Testing Accuracy: 93.55 %

In [34]:
mse_rf = mean_squared_error(y_test, y_pred_rf)

print("Random Forest MSE:", mse_rf)

Random Forest MSE: 5030141.001665953

In [35]:
rmse_rf = np.sqrt(mse_rf)

print("Random Forest RMSE:", rmse_rf)

Random Forest RMSE: 2242.797583748019

In [36]:
mae_rf = mean_absolute_error(y_test, y_pred_rf)

print("Random Forest MAE:", mae_rf)

Random Forest MAE: 1508.426662116248

In [37]:
import pickle

In [38]:
with open("random_forest_model.pkl", "wb") as file:
    pickle.dump(rf_reg, file)

print("random_forest_model.pkl saved successfully!")

random_forest_model.pkl saved successfully!

In [39]:
features = X.columns.tolist()

print("Features:", features)

Features: ['symboling', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'num-of-cylinders', 'engine-size', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg']

In [40]:
with open("features.pkl", "wb") as file:
    pickle.dump(features, file)

print("features.pkl saved successfully!")

features.pkl saved successfully!

In [41]:
with open("random_forest_model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

print("Random Forest model loaded successfully!")

Random Forest model loaded successfully!

In [42]:
with open("features.pkl", "rb") as file:
    loaded_features = pickle.load(file)

print("Features loaded successfully!")
print(loaded_features)

Features loaded successfully!
['symboling', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'num-of-cylinders', 'engine-size', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg']

In [43]:
loaded_prediction = loaded_model.predict(X_test)

loaded_r2 = r2_score(y_test, loaded_prediction)

print("Loaded Random Forest Model Testing Accuracy:",
      round(loaded_r2 * 100, 2), "%")

Loaded Random Forest Model Testing Accuracy: 93.55 %